# Generated by Django 4.2 on 2025-12-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_banner',
            field=models.ImageField(blank=True, null=True, upload_to='episode_banners/'),
        ),
        migrations.AddField(
            model_name='episode',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='season_banner',
            field=models.ImageField(blank=True, null=True, upload_to='season_banners/'),
        ),
    ]
