# Generated by Django 4.2 on 2025-12-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_episode_episode_banner_episode_release_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='release_date',
            new_name='episode_release_date',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='release_date',
            new_name='season_release_date',
        ),
    ]
