# Generated by Django 4.2 on 2025-12-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
