# Generated by Django 4.2 on 2025-12-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_recipient_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_role',
            field=models.CharField(default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
