# Generated by Django 4.2 on 2025-12-26 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_likedvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedvideo',
            options={'ordering': ['-liked_at']},
        ),
        migrations.AddField(
            model_name='likedvideo',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.episode'),
        ),
    ]
