# Generated by Django 4.2 on 2025-12-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_likedvideo_options_likedvideo_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
