# Generated by Django 4.2 on 2025-12-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_episode_episode_description_episode_episode_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
