# Generated by Django 4.2 on 2025-12-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_season_season_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['episode_number']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['season_order']},
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
