# Generated by Django 4.2 on 2026-01-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_notification_redirect_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='redirect_url',
            new_name='redirect_link',
        ),
    ]
