# Generated by Django 4.2 on 2026-01-07 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notification_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likedvideo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='likedvideo',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.season'),
        ),
        migrations.AlterUniqueTogether(
            name='likedvideo',
            unique_together={('customer_username', 'movie', 'web_series', 'season', 'episode')},
        ),
    ]
