# Generated by Django 4.2 on 2025-12-26 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_watchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.episode'),
        ),
    ]
