# Generated by Django 4.2 on 2025-12-26 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_watchhistory_episode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_username', models.CharField(max_length=100)),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.movie')),
                ('web_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.webseries')),
            ],
            options={
                'unique_together': {('customer_username', 'movie', 'web_series')},
            },
        ),
    ]
