# Generated by Django 4.2 on 2026-01-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_redirect_url_notification_redirect_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='redirect_link',
            new_name='redirect_url',
        ),
    ]
