# Generated by Django 4.2 on 2026-01-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='razorpay_receipt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Custom Receipt ID'),
        ),
    ]
