# Generated by Django 4.2 on 2025-12-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminregister',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
